spring:
  application:
    name: my-ai-agent
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:1b
    dashscope:
      api-key: sk-9ac9c6277b4643ccae0773d91e16dcb3
      chat:
        options:
          model: qwen-plus
server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.demo.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
ai:
  apiKey: sk-9ac9c6277b4643ccae0773d91e16dcb3、
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG

